name: Publish releases to PyPI

on:
  release:
    types: [published, prereleased]

jobs:
  build-and-publish:
    name: Builds and publishes releases to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get Version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: "Set version numbmer"
        run: |
          sed -i '/VERSION = /c\VERSION = "${{ steps.get_version.outputs.VERSION }}"' ${{ github.workspace }}/setup.py
      - name: Commit files
        run: |
          if [ $(git diff HEAD | wc -l) -gt 0 ]
          then
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "GitHub Actions"
          git commit -a --amend --no-edit || true
          git push --force || true
          fi
      - name: Set up Python 3.8
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
      - name: Install wheel
        run: >-
          pip install wheel
      - name: Build
        run: >-
          python3 setup.py sdist bdist_wheel
      - name: Publish release to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
